### ISSUE TITLE
SPARQL Endpoint Authentication

### ISSUE THREAD

**Issue by mgberg** [jimjonesbr/rdf_fdw#1]
I'm very excited to use this to access data in triple stores from postgres. However, the triple stores I have require authentication (via basic auth), but it doesn't seem based on your README that credentials for the SPARQL endpoint are supported. Is that true, or did I miss something?

**Comment by jimjonesbr** [comment]
Hi there. Thanks for reaching out!

The user authentication I implemented was indeed something else, namely the authentication in case there is a proxy server between PostgreSQL and the SPARQL endpoint - see [CURLOPT_PROXYUSERPWD](https://curl.se/libcurl/c/CURLOPT_PROXYUSERPWD.html) . I actually never needed to provide credentials to any endpoint I used so far... that's why it didn't crossed my mind :)

Perhaps you could give me some info on how to reproduce your environment, so that I can see if I can implement it.

**Comment by mgberg** [comment]
There are many triple stores out there that require authentication to use their SPARQL endpoints (generally database account credentials), and generally they support HTTP basic auth on requests to the SPARQL endpoint. Example triple stores that behave like this include GraphDB and AllegroGraph, both of which have free versions you could use to test with.

**Comment by jimjonesbr** [comment]
In 19deeb8 I added support for [`CREATE USER MAPPING`](https://www.postgresql.org/docs/current/sql-createusermapping.html). I tested it with a local GraphDB triplestore and first tests worked ok 

```sql
CREATE SERVER graphdb
FOREIGN DATA WRAPPER rdf_fdw 
OPTIONS (endpoint 'http://192.168.178.27:7200/repositories/mgberg',
         format 'application/sparql-results+xml');

CREATE USER MAPPING FOR postgres SERVER graphdb OPTIONS (user 'admin', password '123456');

CREATE FOREIGN TABLE ft (
  s text OPTIONS (variable '?s')
)
SERVER graphdb OPTIONS (sparql 'SELECT * {?s ?p ?o}'); 

SELECT * FROM ft LIMIT 1;

                        s                        
-------------------------------------------------
 http://www.w3.org/1999/02/22-rdf-syntax-ns#type
(1 row)
```

Could you please test it? (it still lacks proper regression tests and documentation)

The CI bot is failing on PostgreSQL 11, but it seems to work on newer versions .... I will take a look at it later.

**Comment by jimjonesbr** [comment]
357c4e9 fixes the `USER MAPPING` issue on PostgreSQL 11

**Comment by mgberg** [comment]
Just tried it out and it works! This is great, thanks.

As a side note, it might be helpful to include in your docs that in order to build the extension, you need to have `make`, `gcc`, `postgresql-server-dev-XX`, and `libcurl-dev` installed. I tried building the extension in a Docker container using the `postgres:lastest` image (since that was the quickest way to get a postgres server running) and had to install those extra packages. Not that people should be building it in the Docker container necessarily, but the full list of dependencies would be good.

Thanks again!

**Comment by jimjonesbr** [comment]
> Just tried it out and it works! This is great, thanks.

Nice :+1: 

> As a side note, it might be helpful to include in your docs that in order to build the extension, you need to have make, gcc, postgresql-server-dev-XX, and libcurl-dev installed. I tried building the extension in a Docker container using the postgres:lastest image (since that was the quickest way to get a postgres server running) and had to install those extra packages. Not that people should be building it in the Docker container necessarily, but the full list of dependencies would be good.

I see. In the [Requirements](https://github.com/jimjonesbr/rdf_fdw?tab=readme-ov-file#requirements) I listed the software dependencies, but not what is necessary to build the software itself (gcc and make). In the [Deploy with Docker](https://github.com/jimjonesbr/rdf_fdw?tab=readme-ov-file#deploy-with-docker) section I added a few commands containing all dependencies, but it can be indeed overlooked if you're not using containers. I'll try to address it in v1.1.0, which I will be releasing soon. Thanks!
